### ISSUE TITLE
Combination string cannot be of equal width  “fi” "fl"

### ISSUE THREAD

**Issue by redisviewer** [mhtvsSFrpHdE/noto-sans-mono-r0#2]
The characters "fi" and "fl" both seem to have this problem

<img width="279" alt="image" src="https://user-images.githubusercontent.com/12822830/211711717-ee4a701f-ecf7-4773-bc95-1f5d141dc610.png">

**Comment by mhtvsSFrpHdE** [comment]
Problem received and may be investigated in next period of time.

**Comment by mhtvsSFrpHdE** [comment]
VSCode are fine, but Windows 10 22H2 notepad will shrink space between fi and fl.

**Comment by mhtvsSFrpHdE** [comment]
https://github.com/ryanoasis/nerd-fonts/issues/254
https://fontforge.org/docs/tutorial/editexample4.html

Let's see...

Element\Font Info\Lookups\liga+\double click\Lookup Subtable\Remove All
View\Label Glyph By\Unicode
Delete all start from fb00 to fb04 (Right click\Clear)

**Comment by mhtvsSFrpHdE** [comment]
@redisviewer https://github.com/mhtvsSFrpHdE/noto-sans-mono-r0/releases/tag/1.1.2

Or you can download from main repository separably.
